spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dbdb
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        open-in-view: false
#        show-sql: true